vlm_api_url: "http://qwen3vl-8b-instruct-fp8:8000/v1"
vlm_api_key: "token-abc"
vlm_model_name: "qwen3vl-8b-instruct-fp8"

temperature: 0.0
presence_penalty: 0.0
repetition_penalty: 1.0

dpi: 150
max_tile_size: 4096
tile_overlap: 120

openwebui_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImU1ODI1ZGYzLWJlMDYtNDZiMS05ZmM0LTdjMzM0Y2EyNGZjYyIsImV4cCI6MTc3MDI4NjExMSwianRpIjoiYWY5ZmU5MjUtNjljNC00ZmM0LThhMzEtYTVkOWUyNzliYjc0In0.ThAFVp7XstVRipJkAM5JW15uBB5wPQkwmGl7cZANsCw"
openwebui_host: "http://open-webui:8080"